spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mariadb://192.168.216.129:3306/v_exam?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root@mariadb
      driver-class-name: org.mariadb.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 20 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      max-lifetime: 1800000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL
      connection-timeout: 60000
      connection-test-query: SELECT 1
      pool-name: vExamDataSourcePool
      read-only: false

#  redis:
#    database: 0
#    host: 192.168.216.200
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0

server:
  port: 8082

UKeyWorker:
  workid: 1
  bizid: 1