spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
swagger2:
  host: localhost:${server.port}
  enable: true