spring:
  profiles:
    active: home

mybatis:
  mapper-locations: classpath:/mybatis-mapper/**Mapper.xml
  config-location: classpath:/mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
swagger2:
  host: localhost
  enable: true